"""empty message

Revision ID: 0ac0e577ef28
Revises: 854b5ab6e19d
Create Date: 2022-06-29 19:34:07.481318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac0e577ef28'
down_revision = '854b5ab6e19d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'user_id')
    # ### end Alembic commands ###
