"""empty message

Revision ID: 4796a8c8a6ea
Revises: 84649c9012c2
Create Date: 2022-06-28 16:22:04.113518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4796a8c8a6ea'
down_revision = '84649c9012c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
