"""empty message

Revision ID: 84649c9012c2
Revises: 51d105449ac2
Create Date: 2022-06-28 16:13:56.652292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84649c9012c2'
down_revision = '51d105449ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
