"""empty message

Revision ID: 8ce715be7ef5
Revises: 4796a8c8a6ea
Create Date: 2022-06-29 12:57:01.799070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce715be7ef5'
down_revision = '4796a8c8a6ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_item', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_item', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('order_item_product_id_fkey', 'order_item', type_='foreignkey')
    op.drop_constraint('order_item_order_id_fkey', 'order_item', type_='foreignkey')
    op.create_foreign_key(None, 'order_item', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_item', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.create_foreign_key('order_item_order_id_fkey', 'order_item', 'order', ['order_id'], ['id'])
    op.create_foreign_key('order_item_product_id_fkey', 'order_item', 'product', ['product_id'], ['id'])
    op.alter_column('order_item', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_item', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
