"""empty message

Revision ID: f929d13b62fa
Revises: aef687f98848
Create Date: 2022-07-13 06:21:32.267325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f929d13b62fa'
down_revision = 'aef687f98848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('address_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order', 'address', ['address_id'], ['id'], ondelete='CASCADE')
    op.drop_column('order', 'country')
    op.drop_column('order', 'address')
    op.drop_column('order', 'city')
    op.drop_column('order', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('state', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('address', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('country', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'address_id')
    # ### end Alembic commands ###
